---
title: "UMD's Land Grab History"
author: "Ethan Huegler"
date: "3/2/2021"
output:
  html_document:
    code_folding: hide
---

```{r, setup, include=FALSE}
library(dplyr)
library(rgdal)
library(broom)
library(ggplot2)
library(gganimate)
library(transformr)
library(ggrepel)
```


```{r, data, message = false}
path <- "https://raw.githubusercontent.com/HCN-Digital-Projects/landgrabu-data/master/Morrill_Act_of_1862_Indigenous_Land_Parcels_Database/CSVs/Cessions.csv"
cessions <- read.csv(path)

path <- "https://raw.githubusercontent.com/HCN-Digital-Projects/landgrabu-data/master/Morrill_Act_of_1862_Indigenous_Land_Parcels_Database/CSVs/Parcels.csv"
parcels <- read.csv(path)

path <- "https://raw.githubusercontent.com/HCN-Digital-Projects/landgrabu-data/master/Morrill_Act_of_1862_Indigenous_Land_Parcels_Database/CSVs/Universities.csv"
universities <- read.csv(path)

path <- "https://github.com/ehuegler/landgrabu-mirror/blob/master"
path <- "C:\\Users\\ethan\\Downloads\\test"
parcel_shapes <- readOGR(dsn = path, layer = "Parcel_Polygons", verbose = FALSE)


```


```{r, plotting}
rescale <- function(x, from, to) {
  maxx <- max(x)
  minx <- min(x)
  out <- (to - from) * (x - minx)
  out <- out / (maxx - minx)
  out + from
}

umd <- "University of Maryland"

plot_univ <- function(univ = "University of Maryland") {} 
umd_parcels <- filter(parcels, University == umd)

umd_parcel_shapes <- parcel_shapes[parcel_shapes$MTRSA_LG %in% umd_parcels$MTRSA_LG,]
umd_parcel_shapes_data <- tidy(umd_parcel_shapes)
s <- umd_parcel_shapes_data %>% group_by(id) %>% summarise(lat = mean(lat), long = mean(long))

i <- 1
while (i <= nrow(s)) {
  s[i,4] <- umd_parcel_shapes@data[which(umd_parcel_shapes@data[,1] == (as.integer(s[i,1]) + 1)),2]
  s[i,5] <- umd_parcels[which(umd_parcels[,1] ==  as.character(s[i,4])),15]
  s[i,6] <- umd_parcels[which(umd_parcels[,1] ==  as.character(s[i,4])),10]
  s[i,7] <- umd_parcels[which(umd_parcels[,1] ==  as.character(s[i,4])),4]
  i <- i + 1
}

colnames(s) <- c(colnames(s)[1:3], "MTRSA_LG", "date", "tribe", "acres")
s$date <- as.Date(s$date, "%Y%m%d")
s[is.na(s)] <- as.Date("1864-01-01")
s <- s[order(s$date),]
s[,"cummulative_acres"] <- cumsum(s$acres)

acres_over_time <- s %>% group_by(date) %>% summarise(acres = as.integer(max(cummulative_acres)))

us_states <- map_data("state")

map <- ggplot() +
  # Map of US
  geom_polygon(data = us_states, aes(x = long, y = lat, group = group),
               color = "black",
               fill = "lightgrey") +
  # UMD dot
  geom_point(aes(y = 38.990267, x = -76.943949), color = "#CF102D", size = 3) +
  geom_label_repel(data = data.frame(y = 38.990267, x = -76.943949), 
                   aes(x, y), 
                   label = "UMD",
                   seed = 10) +
  # Locations
  geom_point(data = s, aes(x = long, y = lat, group = id, color = factor(tribe)),
             size = 4) +
  # Acre Line
  geom_line(data = acres_over_time, 
            aes(x = rescale(as.integer(acres), min(us_states$long), max(us_states$long)), 
                y = min(us_states$lat) - 10),
            color = "#CF102D",
            size = 2) +
  # Acre line point
  geom_point(data = acres_over_time, 
            aes(x = rescale(as.integer(acres), min(us_states$long), max(us_states$long)), 
                y = min(us_states$lat) - 10),
            size = 4,
            color = "#CF102D") +
  #Acre labels
  geom_label_repel(data = acres_over_time, 
                  aes(x = rescale(as.integer(acres), min(us_states$long), max(us_states$long)), 
                      y = min(us_states$lat) - 10,
                      label = as.integer(acres),
                      group = 1), 
                  max.overlaps = 20) +
  # Style stuff
  theme_void() +
  theme(legend.position = "bottom", 
        legend.key=element_blank(), 
        legend.key.size=unit(1,"point"),
        axis.title.x.bottom = element_text()) +
  guides(color = guide_legend(override.aes = list(size=5), nrow = 26)) +
  labs(title = "US Map!",
       color = "Tribe",
       x = "Total Acres Aquired by University of Maryland by {frame_along}")

map





```

